@startuml
title Detail Class PackageHistory

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class PackageHistory {
  - id: Int
  - userId: Int
  - packageId: Int
  - startedAt: DateTime
  - endedAt: DateTime
  - reason: String
  - createdAt: DateTime
  --
  + changeUserPackage()
  + verifyPaymentNotification()
}

PackageHistory --> User
PackageHistory --> Package
@enduml
