@startuml
title Detail Class TicketSurvey

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class TicketSurvey {
  - id: Int
  - surveyTicketId: Int
  - installationTicketId: Int
  - plannedItems: Json
  - actualItems: Json
  - notes: String
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + completeSurvey()
  + reportSurveyActual()
  + getSurveyByTicket()
  + updateSurvey()
}

TicketSurvey --> Ticket
@enduml
