@startuml
title Detail Class CategoryPackage

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class CategoryPackage {
  - id: Int
  - name: String
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + createCategory()
  + getAllCategories()
  + getCategoryById()
  + updateCategory()
  + deleteCategory()
}
@enduml
