@startuml
title Detail Class Profile

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class Profile {
  - id: Int
  - user_id: Int
  - phone_number: String
  - image_url: String
  - full_address: String
  - province: String
  - city: String
  - district: String
  - subdistrict: String
  - latitude: Float
  - longitude: Float
  - routerId: Int
  - pppUsername: String
  - pppPassword: String
  - pppProfile: String
  - isPppActive: Boolean
  --
  + meProfile()
  + updateProfile()
  + updateEmail()
  + updatePassword()
  + changePackage()
}

Profile --> User
Profile --> Router
@enduml
