@startuml
title Detail Class TicketTechnicianMember

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class TicketTechnicianMember {
  - id: Int
  - ticketId: Int
  - technicianId: Int
  - createdAt: DateTime
  --
  + assignTicket()
  + updateTicketMembers()
}

note right of TicketTechnicianMember
Di Prisma diimplementasikan
sebagai model TicketMember.
end note

TicketTechnicianMember --> Ticket
TicketTechnicianMember --> User
@enduml
