@startuml
title Detail Class CoveredArea

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class CoveredArea {
  - id: Int
  - province: String
  - city: String
  - district: String
  - village: String
  - fullAddress: String
  - radius_m: Int
  - center: Geography
  - createdAt: DateTime
  --
  + checkAvailability()
  + checkAvailabilityNoHistory()
  + addCoveredArea()
  + updateCoveredArea()
  + getAllCoveredAreas()
  + deleteCoveredArea()
}

CoveredArea ..> CoverageCheckHistory
@enduml
