@startuml
title Detail Class Router

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class Router {
  - id: Int
  - name: String
  - host: String
  - user: String
  - password: String
  - port: Int
  - portApi: Int
  - portSsh: Int
  - pppLocalAddress: String
  - pppRemoteAddress: String
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + create()
  + getAll()
  + getById()
  + update()
  + remove()
  + testConnection()
  + getActiveUsers()
  + addPppSecret()
  + disablePppSecret()
  + enablePppSecret()
  + createPppSecret()
  + syncPackageToRouter()
  + syncAllPackagesToRouter()
}

Router "1" -- "*" Profile
@enduml
