@startuml
title Detail Class User

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class User {
  - id: Int
  - email: String
  - fullname: String
  - password: String
  - role: Role
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + registerUser()
  + loginUser()
  + logoutUser()
  + listUsers()
  + getUser()
  + createUser()
  + updateUser()
  + deleteUser()
  + resetPassword()
}

class "«enumeration»\nRole" as Role {
  CUSTOMER
  TECHNICIAN
  TECH_ADMIN
}

User ..> Role
@enduml
