@startuml
title Detail Class SuspensionHistory

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class SuspensionHistory {
  - id: Int
  - userId: Int
  - reason: String
  - suspendedAt: DateTime
  - resumedAt: DateTime
  - createdAt: DateTime
  --
  + applyOverdueSuspension()
  + payLatest()
}

SuspensionHistory --> User
@enduml
