@startuml
title Detail Class TicketAttachment

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class TicketAttachment {
  - id: Int
  - ticketId: Int
  - filename: String
  - mimeType: String
  - dataUrl: String
  - createdAt: DateTime
  --
  + createTicket()
  + updateStatus()
  + completeSurvey()
  + reportSurveyActual()
}

TicketAttachment --> Ticket
@enduml
