@startuml
title Detail Class TicketCategory

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class TicketCategory {
  - id: Int
  - name: String
  - isExpirable: Boolean
  - expireHours: Int
  - requiresTechnician: Boolean
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + list()
  + create()
  + update()
  + remove()
}
@enduml
