@startuml
title Detail Class Package

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class Package {
  - id: Int
  - name: String
  - price: Float
  - downloadSpeed: Float
  - uploadSpeed: Float
  - isPopular: Boolean
  - description: String
  - metadata: Json
  - categoryId: Int
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + createPackage()
  + getAllPackages()
  + getPackageById()
  + updatePackage()
  + deletePackage()
  + syncAllPackagesToAllRouters()
  + recommendPackage()
}

Package --> CategoryPackage
@enduml
