@startuml
title Detail Class InventoryItem

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide circle

class InventoryItem {
  - id: Int
  - name: String
  - stock: Int
  - unit: String
  - categoryId: Int
  - createdAt: DateTime
  - updatedAt: DateTime
  --
  + createItem()
  + getAllItems()
  + getItemById()
  + updateItem()
  + deleteItem()
  + completeSurvey()
  + reportSurveyActual()
}

InventoryItem --> InventoryCategory
@enduml
